spring:
#  config:
#    import: open-api.yml
  mvc:
    static-path-pattern: /static/**

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /h2
      enabled: true

  datasource:
    write:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:~/h2db/tax
      username:
      password:
      maximumPoolSize: 30
      minimumIdle: 5
      poolName: writedbjobis
      readOnly: false
    read:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:~/h2db/tax
      username:
      password:
      maximumPoolSize: 30
      minimumIdle: 5
      poolName: readdbjobis
      readOnly: true
#  sql:
#    init:
#      data-locations: classpath:sql/sample-ranking-data.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    operationsSorter: method
    apisSorter: alpha
  default-produces-media-type: application/json

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dX

feign:
  client:
    config:
      default:
        connectTimeout: 60_000
        readTimeout: 3_000
    default-to-properties: false # @Configuration 설정으로 인해 default설정이 override 되지 못하게 함

server:
  tomcat:
    threads:
      max: 2000
  forward-headers-strategy: FRAMEWORK

cache:
  maximum-size: 100
  duration: 3000

logging:
  level:
    root: DEBUG
    com.jobis.tax: DEBUG
